services:
  azurite:
    build:
      context: ./Azurite-3.35.0
      dockerfile: Dockerfile
    image: azurite:latest
    #image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite-emulator
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service
      - "10002:10002"  # Table service
    volumes:
      - azurite-data:/data
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data --debug /data/debug.log
    healthcheck:
      test: ["CMD-SHELL", "code=$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:10000/ || echo 000) && [ \"$code\" != \"000\" ]"]
      #test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:10000/ | grep -qE '2..|3..|4..|5..'"]
      #test: ["CMD", "curl", "-f", "http://localhost:10000/ || exit 1"]
      #test: ["CMD", "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}", "http://localhost:10000/devstoreaccount1?comp=list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    #healthcheck:
      #test: ["CMD", "nc", "-z", "localhost", "10000"]
      #interval: 30s
      #timeout: 10s
      #retries: 3
      #start_period: 10s

  solace-broker:
    image: solace/solace-pubsub-standard:latest
    container_name: solace-broker
    hostname: solace-broker
    ports:
      - "8095:8080"   # Web admin console
      - "55555:55555" # SMF port
      - "8008:8008"   # Web messaging
      - "1943:1943"   # MQTT port
      - "8445:8443"   # Web admin HTTPS
      - "9443:9443"   # REST messaging HTTPS
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - system_scaling_maxconnectioncount=100
    shm_size: 2g
    ulimits:
      core: -1
      nofile:
        soft: 65536
        hard: 1048576
    healthcheck:
      test: ["CMD", "bash", "-c", "timeout 3 bash -c '</dev/tcp/localhost/55555'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  solace-init:
    image: curlimages/curl:latest
    container_name: solace-init
    volumes:
      - ./init-solace-queue.sh:/init-solace-queue.sh:ro
    entrypoint: ["/bin/sh", "/init-solace-queue.sh"]
    environment:
      - SOLACE_HOST=solace-broker
      - SOLACE_PORT=8080
      - SOLACE_USER=admin
      - SOLACE_PASS=admin
      - VPN_NAME=default
      - QUEUE_NAME=test/topic
      - TOPIC_NAME=test/topic
    depends_on:
      solace-broker:
        condition: service_healthy

  solace-service:
    build: .
    container_name: solace-service-app
    ports:
      - "8091:8080"  # App on different port to avoid conflict with Solace admin
    environment:
      - SOLACE_ENABLED=true
      - SOLACE_HOST=tcp://solace-broker:55555
      - SOLACE_USERNAME=default
      - SOLACE_PASSWORD=default
      - SOLACE_VPN=default
      - SOLACE_QUEUE_NAME=test/topic
      - SOLACE_TOPIC=test/topic
      - AZURE_STORAGE_ENABLED=true
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      - AZURE_STORAGE_CONTAINER_NAME=solace-messages
    depends_on:
      solace-broker:
        condition: service_healthy
      azurite:
        condition: service_healthy
      solace-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "bash", "-c", "timeout 3 bash -c '</dev/tcp/localhost/8080'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  azurite-data:
