apiVersion: v1
kind: ConfigMap
metadata:
  name: container-azm-ms-agentconfig
  namespace: kube-system
data:
  schema-version: v1
  config-version: ver1
  log-data-collection-settings: |-
    [log_collection_settings]
      [log_collection_settings.stdout]
        enabled = true
        exclude_namespaces = ["kube-system", "kube-public"]
      [log_collection_settings.stderr]
        enabled = true
        exclude_namespaces = ["kube-system", "kube-public"]
      [log_collection_settings.env_var]
        enabled = true
  prometheus-data-collection-settings: |-
    [prometheus_data_collection_settings.cluster]
      interval = "1m"
      monitor_kubernetes_pods = true
    [prometheus_data_collection_settings.node]
      interval = "1m"
  metric_collection_settings: |-
    [metric_collection_settings.collect_kube_system_pv_metrics]
      enabled = true
---
# Application Insights configuration via environment variable
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-insights-config
  namespace: solace-service
data:
  # Application Insights connection string
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=${APPINSIGHTS_INSTRUMENTATION_KEY};IngestionEndpoint=https://${AZURE_REGION}.in.applicationinsights.azure.com/;LiveEndpoint=https://${AZURE_REGION}.livediagnostics.monitor.azure.com/"
  APPLICATIONINSIGHTS_ROLE_NAME: "solace-service"
  # Enable auto-instrumentation
  JAVA_TOOL_OPTIONS: "-javaagent:/opt/applicationinsights-agent.jar"
