apiVersion: v1
kind: ServiceAccount
metadata:
  name: solace-service-sa
  namespace: solace-service
  annotations:
    # Azure Workload Identity annotation
    azure.workload.identity/client-id: "${AZURE_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${AZURE_TENANT_ID}"
  labels:
    azure.workload.identity/use: "true"
---
# For legacy AAD Pod Identity (if not using Workload Identity)
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: solace-service-identity
  namespace: solace-service
spec:
  type: 0  # User-assigned managed identity
  resourceID: "${AZURE_IDENTITY_RESOURCE_ID}"
  clientID: "${AZURE_CLIENT_ID}"
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: solace-service-identity-binding
  namespace: solace-service
spec:
  azureIdentity: solace-service-identity
  selector: solace-service
