apiVersion: v1
kind: Service
metadata:
  name: solace-service
  namespace: solace-service
  labels:
    app: solace-service
spec:
  type: NodePort
  selector:
    app: solace-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30080  # External access port
