---
apiVersion: v1
kind: Service
metadata:
  name: azurite
  namespace: solace-service
  labels:
    app: azurite
spec:
  type: NodePort
  selector:
    app: azurite
  ports:
  - name: blob
    port: 10000
    targetPort: 10000
    nodePort: 30100
  - name: queue
    port: 10001
    targetPort: 10001
    nodePort: 30101
  - name: table
    port: 10002
    targetPort: 10002
    nodePort: 30102

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurite-data
  namespace: solace-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  namespace: solace-service
  labels:
    app: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
      - name: azurite
        image: mcr.microsoft.com/azure-storage/azurite:latest
        imagePullPolicy: IfNotPresent
        args:
        - azurite
        - --blobHost
        - "0.0.0.0"
        - --queueHost
        - "0.0.0.0"
        - --tableHost
        - "0.0.0.0"
        - --location
        - /data
        - --debug
        - /data/debug.log
        ports:
        - name: blob
          containerPort: 10000
          protocol: TCP
        - name: queue
          containerPort: 10001
          protocol: TCP
        - name: table
          containerPort: 10002
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          tcpSocket:
            port: 10000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 10000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: azurite-data
