apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solace-service

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: solace-service
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: messaging-platform

images:
  - name: solace-service
    newName: your-registry/solace-service
    newTag: latest
