apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: solace-service
  namespace: solace-service
  labels:
    app: solace-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: solace-service
